// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eukrtmjmkwxcprvveljg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1a3J0bWpta3d4Y3BydnZlbGpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDkzMzYsImV4cCI6MjA2NDY4NTMzNn0.KUS6QaM1ETOGLA3dxR3GU5vg8mT27bXYP_5-fPQQZxs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);